:pencil: chisel + verilator
hitszosa/wiki pull request #60
Opened 2024-05-26 15:13 UTC by KINGFIOX

2024-05-26 15:17 UTC, shirok1 commented
有些拼写不太规范（大小写）

2024-05-26 15:38 UTC, Origami404 requested changes
请至少修改编译安装 verilator 片段, 或给出它确实在大部分情况下就是需要编译安装的理由

2024-05-26 15:38 UTC, Origami404 commented on docs/popular-science/bash-dlc.md
> +大括号内还可以写数字/字符 + 增长，比如 `{x..y[..incr]}`
不妨直接修改为 "大括号内还可以写所需数字或字符的范围: `{begin..end[..incr]}` (步长是可选的)"

2024-05-26 15:38 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +## 安装 verilator
在某些发行版中 verilator 有包, 比如 Archlinux 中有 `extra/verilator`, 可以在 Repology 中查询具体名单: https://repology.org/project/verilator/versions

2024-05-26 15:38 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +## 安装 verilator
如非特别必要, 我强烈反对源码编译安装到 `/usr` 的行为, 请修改此段, 以 "将 verilator 安装至某个目录下并增加 PATH" 替代之, 并指出只有在所在 distro 的包管理器中没有适合版本的 verilator 包时才需进行此操作.

```
./configure --prefix=$HOME/app/verilator 
make -j `nproc`                          
make install
echo 'export PATH=$PATH:$HOME/app/verilator/bin' >> .bashrc
```

2024-05-26 15:38 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +```sh
可以补充更多 distro 中对应的包名: https://repology.org/project/gtkwave/versions

2024-05-26 15:38 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +然后在 vscode 中打开我们的 chisel 就行了。当然也可以用其他的 IDE (neovim is the best ide in the world!)
是否指出 vscode 所用的 scala lsp? 以及个人观察是对于稍微大一些的 chisel 项目 (小学期级别), VSCode + Metals 会很卡, 建议使用 JetBrain IDEA

2024-05-26 15:38 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +## 调试 chisel 生成的 verilog
建议补充具体的命令和代码, 比如一小段 chisel 生成 verilog 的代码和一两行 verilator 运行代码以及出来的仿真可执行文件需要如何运行

2024-05-26 15:39 UTC, Origami404 commented
BTW, 如果你感兴趣的话可以看看这个仓库: https://github.com/Origami404/MiniRV-Chisel

2024-05-26 15:54 UTC, KINGFIOX commented on docs/popular-science/bash-dlc.md
> +大括号内还可以写数字/字符 + 增长，比如 `{x..y[..incr]}`
这个是 autocorrect 搞的

2024-05-27 13:37 UTC, Origami404 approved these changes
LGTM, thanks

2024-05-27 13:37 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +如果是 ssh 连接的 linux，可以使用 CyberDuck 或者是 MountainDuck（付费）或者是 sshfs 挂载目录，然后在 宿主机上 `gtkwave <.vcd>` 或者是双击打开。（笔者就是用的这种方式）
说起来, 之前 @rewired-gh 教过我一个东西: 如何让 gtkwave 打开的时候把所有信号都展示出来. 原理大概是写一个 tcl 脚本来调 gtkwave:

```tcl
# add_all_and_zoom_full.tcl
# Add all signals
set nfacs [ gtkwave::getNumFacs ]
set all_facs [list]
for {set i 0} {$i < $nfacs } {incr i} {
  set facname [ gtkwave::getFacName $i ]
  lappend all_facs "$facname"
}
set num_added [ gtkwave::addSignalsFromList $all_facs ]
puts "num signals added: $num_added"

# Zoom full
gtkwave::/Time/Zoom/Zoom_Full

# Print
# set dumpname [ gtkwave::getDumpFileName ]
# gtkwave::/File/Print_To_File PDF {Letter (8.5" x 11")} Minimal $dumpname.pdf
```

然后:

```bash
gtkwave add_all_and_zoom_full.tcl <.vcd> 2> /dev/null
```

有需要的话可以加上这一段.

2024-05-27 14:05 UTC, SoraShu requested changes
主要问题是一些英文拼写问题，请参考 [规范英文拼写](https://wiki.osa.moe/contribute-guide/markdown/#%E8%A7%84%E8%8C%83%E8%8B%B1%E6%96%87%E6%8B%BC%E5%86%99) 进行修改。

并未列出所有问题。

2024-05-27 14:05 UTC, SoraShu commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +mac 需要安装 homebrew 作为包管理器，请查阅: https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/
Homebrew

2024-05-27 14:05 UTC, SoraShu commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +bison 和 flex 是 gnu 提供的两个语法解析工具。
GNU

2024-05-27 16:12 UTC, SoraShu approved these changes

2024-05-27 16:21 UTC, merged