简化了一些branch
hitszosa/wiki pull request #63
Opened 2024-05-28 02:43 UTC by KINGFIOX

2024-05-28 18:02 UTC, Origami404 requested changes

2024-05-28 18:02 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +比较灵活的方式是：将 server 的`<chisel-project>`目录挂载到 client 上，然后在 client 的 mount point 处通过 GTKWave 打开。
既然已经有 "远端"/"本地" 二词可以指代两台机器, 无需再额外定义 server/client, 其他语句也不是很通顺. 可以写为:

远端机器上通常没有桌面环境, 当我们连接到远端机器开发时, 肯定是不能指望直接在远端机器上执行 `gtkwave <.vcd>` 就能在本地弹出一个窗口出来的. 自然, 我们可以为远端机器安装桌面环境和配置 X-Forward. 但倘若只是想用 GTKWave 查看波形, 那么将波形文件以某种方式下载到本地, 再使用本地的 GTKWave 打开查看显然是更合理的选择.

但每次重新运行仿真都要手动通过 VSCode 或 scp 下载波形文件确实令人烦躁, 那么应该如何快捷地将远端的某个文件下载或同步到本地呢? 我们可以使用 sshfs (此处可能需要一个它的配置链接) 或基于它的其他软件将远端的目录直接挂载到本地, 每次本地打开挂载点内文件时自动从远端拉取文件内容, 从而便利我们在本地使用 GTKWave 查看波形.

2024-05-29 10:51 UTC, shirok1 commented
刚刚发现这个 pr 是 [hitszosa:dev/unofficial-lab-env-comp-organ-lab2](https://github.com/hitszosa/wiki/tree/dev/unofficial-lab-env-comp-organ-lab2) from [KINGFIOX:dev/unofficial-lab-env-comp-organ-lab2](https://github.com/KINGFIOX/hitsz-osa-wiki/tree/dev/unofficial-lab-env-comp-organ-lab2) 的，并不是合到主线，要不要先合了然后我们慢慢改 @Origami404

2024-05-29 11:25 UTC, KINGFIOX commented
等一下，我在改，先别合

2024-05-30 11:22 UTC, kowyo commented on docs/unofficial-lab-env/comp-organ-lab2.md
>  MacOS 需要安装 Homebrew 作为包管理器，请查阅 [Tuna Mirrors 的安装指南](https://mirrors.tuna.tsinghua.edu.cn/help/homebrew) 。
MacOS is a typo, should use macOS.

2024-05-30 11:23 UTC, shirok1 approved these changes
我希望尽快合到仓库中的 dev 分支然后慢慢改

2024-05-30 11:27 UTC, Origami404 requested changes

2024-05-30 11:27 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
>  - Verilator
按本节标题, Verilator 应该从该列表中删去

2024-05-30 11:27 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +我们可以用 C++ 编写一个软件的 golden model 作为对照。
"软件的" 和 "golden model" 是否有语义重复问题 (类似于 "他四处东张西望地看")? Golden model 本身语义上就含有 "软件实现的标准逻辑模型" 之意.

2024-05-30 11:27 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +然而，此仓库中维护的 GTKWave 并不包含 TCL 脚本支持，无法使用[上文](链接)提到的便利方法，因此并不推荐使用这种方式安装。
我的意思是这里给一个到 "使用 TCL 脚本" 小节的链接

2024-05-30 11:27 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +自然，我们可以为远端机器安装桌面环境和配置 X-Forward。配置步骤如下：
不建议把在远端安装 X 环境部分作为这篇文章的一部分, 这种解决方法的分支引入了过多额外工作, 一般人不会这样配的

2024-05-30 11:27 UTC, Origami404 commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +自然，我们可以为远端机器安装桌面环境和配置 X-Forward。配置步骤如下：
值得注意的是 WSL2 现在应该是有自带的 X-Forward 和 X Server 功能, 在 WSL2 上直接安装 X 环境和 GTKWave 是可以直接在宿主 Windows 系统上启动窗口的

2024-05-30 11:31 UTC, KINGFIOX commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +然而，此仓库中维护的 GTKWave 并不包含 TCL 脚本支持，无法使用[上文](链接)提到的便利方法，因此并不推荐使用这种方式安装。
嗷嗷，抱歉抱歉。没注意到

2024-05-30 11:34 UTC, KINGFIOX commented on docs/unofficial-lab-env/comp-organ-lab2.md
>  MacOS 需要安装 Homebrew 作为包管理器，请查阅 [Tuna Mirrors 的安装指南](https://mirrors.tuna.tsinghua.edu.cn/help/homebrew) 。
ok

2024-05-30 11:36 UTC, KINGFIOX commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +我们可以用 C++ 编写一个软件的 golden model 作为对照。
我之前是不知道golden  model 这个名词的，sry

2024-05-30 11:39 UTC, KINGFIOX commented on docs/unofficial-lab-env/comp-organ-lab2.md
> +自然，我们可以为远端机器安装桌面环境和配置 X-Forward。配置步骤如下：
但是，我这里已经放入附录中了，我觉得这会是一个问题。我之前也是不知道可以x-forward的（

2024-05-30 12:10 UTC, merged